# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

before_install:
 - if [ "$TRAIVS_OS_NAME" = "xenial"]; then sudo apt-get -y install libgs10
os:
  - linux
  - osx

r:
  - oldrel
  - release
