# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

before_install:
  - devtools::install_deps(dependencies = TRUE, upgrade = "always")

os:
  - linux
  - osx

r:
  - oldrel
  - release

addons:
  apt:
    - libgsl2
