# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

before_install:
  - R -e 'source("https://install-github.me/r-lib/remotes")'

os:
  - linux
  - osx

r:
  - oldrel
  - release

addons:
  apt:
    - libgsl23
    - libgslcblas0
    - libgsl0-dev
    - libxml2-dev
    - pandoc
