# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

before_install:
 - if [ "$TRAIVS_OS_NAME" = "linux"]; then sudo apt-get -y install libgsl-dev
 - if ["$TRAVIS_OS_NAME" = "linux"]; then sudo apt-get -y install pandoc
 - if ["$TRAVIS_OS_NAME" = "linux"]; then sudo apt-get -y install libxm12-dev
os:
  - linux
  - osx

r:
  - oldrel
  - release
