# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

os:
  - linux
        before_install:
         - sudo apt-get -y install libgs10-dev
  - osx

r:
  - oldrel
  - release
